// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: greeter.proto

package com.jewel.meta.asset_platform.proto.greeter_service;


@SuppressWarnings("all")
public class GreeterServiceProtocolValidator {
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		
		if (clazz.equals(com.jewel.meta.asset_platform.proto.greeter_service.GreeterServiceProtocol.HelloRequest.class)) return new HelloRequestValidator();
		if (clazz.equals(com.jewel.meta.asset_platform.proto.greeter_service.GreeterServiceProtocol.HelloReply.class)) return new HelloReplyValidator();
		return null;
	}


/**
	 * Validates {@code HelloRequest} protobuf objects.
	 */
	public static class HelloRequestValidator implements io.envoyproxy.pgv.ValidatorImpl<com.jewel.meta.asset_platform.proto.greeter_service.GreeterServiceProtocol.HelloRequest> {
		
	
	

	public void assertValid(com.jewel.meta.asset_platform.proto.greeter_service.GreeterServiceProtocol.HelloRequest proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for Name

	
	}
}
/**
	 * Validates {@code HelloReply} protobuf objects.
	 */
	public static class HelloReplyValidator implements io.envoyproxy.pgv.ValidatorImpl<com.jewel.meta.asset_platform.proto.greeter_service.GreeterServiceProtocol.HelloReply> {
		
	
		
	
	

	public void assertValid(com.jewel.meta.asset_platform.proto.greeter_service.GreeterServiceProtocol.HelloReply proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			io.envoyproxy.pgv.StringValidation.length(".greeter.HelloReply.message", proto.getMessage(), 5);
	
			// Validate time
			if (proto.hasTime()) index.validatorFor(proto.getTime()).assertValid(proto.getTime());
	
	}
}
}

